version: '3.3'

services:
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: produto
      MYSQL_ROOT_PASSWORD: password

  adminer:
    image: phpmyadmin:latest
    container_name: admin
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      PMA_ARBITRARY: 1
    links:
      - database
